import React, { useState, useEffect } from 'react';
import { 
  BookOpen, 
  Search, 
  Sparkles, 
  GraduationCap, 
  CheckCircle2, 
  AlertCircle, 
  Clock, 
  ArrowRight,
  ShieldCheck,
  RefreshCw,
  Bookmark
} from 'lucide-react';
import { api } from '../services/api';

export const LearnView: React.FC = () => {
  const [searchTopic, setSearchTopic] = useState('Total Knee Replacement');
  const [activeTopic, setActiveTopic] = useState('Total Knee Replacement');
  const [lessonContent, setLessonContent] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const suggestedTopics = [
    'Total Knee Replacement',
    'ACL Recovery',
    'Meniscus Tear Rehab',
    'Rotator Cuff Healing',
    'Achilles Tendonitis',
    'Patellar Tracking'
  ];

  const fetchLesson = async (topicToFetch: string) => {
    setIsLoading(true);
    setActiveTopic(topicToFetch);
    try {
      const res = await api.getEducationLesson(topicToFetch);
      setLessonContent(res.lesson);
    } catch (err) {
      console.warn('Error fetching lesson:', err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchLesson('Total Knee Replacement');
  }, []);

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchTopic.trim()) return;
    fetchLesson(searchTopic.trim());
  };

  return (
    <div className="pb-24 pt-4 px-4 max-w-md mx-auto space-y-5 animate-in fade-in duration-300">
      {/* Header */}
      <div>
        <div className="flex items-center gap-1.5 text-xs font-semibold text-teal-700 uppercase tracking-wider">
          <GraduationCap className="w-4 h-4" />
          <span>Patient Rehabilitation Education</span>
        </div>
        <h1 className="text-2xl font-extrabold text-slate-800 tracking-tight mt-1">
          Physio Professor
        </h1>
        <p className="text-xs text-slate-500 mt-0.5">
          Plain-language injury guides and recovery blueprints generated by TeachingAgent.
        </p>
      </div>

      {/* Search Bar */}
      <form onSubmit={handleSearchSubmit} className="relative">
        <input
          type="text"
          value={searchTopic}
          onChange={(e) => setSearchTopic(e.target.value)}
          placeholder="Search injury or recovery guide (e.g., ACL Recovery)..."
          className="w-full py-3 pl-10 pr-24 bg-white border border-slate-200/80 rounded-2xl text-xs font-medium placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-teal-500/20 focus:border-teal-500 shadow-2xs"
        />
        <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-3.5" />
        <button
          type="submit"
          disabled={isLoading || !searchTopic.trim()}
          className="absolute right-1.5 top-1.5 bottom-1.5 px-3 bg-teal-600 hover:bg-teal-700 disabled:opacity-50 text-white rounded-xl text-xs font-bold transition-all shadow-xs"
        >
          {isLoading ? (
            <RefreshCw className="w-3.5 h-3.5 animate-spin" />
          ) : (
            'Explain'
          )}
        </button>
      </form>

      {/* Suggested Topic Chips */}
      <div className="space-y-1.5">
        <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider block">
          Popular Patient Guides
        </span>
        <div className="flex flex-wrap gap-1.5">
          {suggestedTopics.map((topic) => {
            const isSelected = activeTopic.toLowerCase() === topic.toLowerCase();
            return (
              <button
                key={topic}
                type="button"
                onClick={() => {
                  setSearchTopic(topic);
                  fetchLesson(topic);
                }}
                className={`text-xs px-3 py-1.5 rounded-full border transition-all ${
                  isSelected
                    ? 'bg-teal-600 text-white border-teal-600 shadow-xs font-semibold'
                    : 'bg-white text-slate-600 border-slate-200 hover:border-teal-300'
                }`}
              >
                {topic}
              </button>
            );
          })}
        </div>
      </div>

      {/* Lesson Content Viewer */}
      <div className="bg-white rounded-3xl p-5 border border-slate-200/80 shadow-[0_2px_12px_rgba(0,0,0,0.04)] space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-teal-50 text-teal-700 rounded-xl">
              <BookOpen className="w-4 h-4" />
            </div>
            <div>
              <span className="text-[10px] font-bold text-teal-700 uppercase tracking-wider block">
                Educational Guide
              </span>
              <h2 className="font-extrabold text-sm text-slate-800">
                {activeTopic}
              </h2>
            </div>
          </div>
          <span className="text-[10px] px-2 py-0.5 rounded-full font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
            TeachingAgent Active
          </span>
        </div>

        {isLoading ? (
          <div className="py-12 flex flex-col items-center justify-center space-y-3">
            <RefreshCw className="w-6 h-6 text-teal-600 animate-spin" />
            <p className="text-xs text-slate-400 font-medium">
              Generating clinical guide for {activeTopic}...
            </p>
          </div>
        ) : (
          <div className="prose prose-sm max-w-none text-slate-700 text-xs leading-relaxed space-y-3 whitespace-pre-line">
            {lessonContent}
          </div>
        )}

        <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-[11px] text-slate-400">
          <span className="flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5 text-teal-600" />
            Vetted for Patient Safety
          </span>
          <span>No medical jargon</span>
        </div>
      </div>
    </div>
  );
};
